### ISSUE TITLE
Issue when mounting buckets with a dot "." inside.

### ISSUE THREAD

**Issue by omnecon** [danilop/yas3fs#138] opened 2016-11-11 06:30 UTC
I tried to mound a bucket: s3://aaa.bbb.ccc with the following command:

yas3fs -d --s3-use-sigv4 --s3-endpoint s3.eu-central-1.amazonaws.com --region eu-central-1 s3://aaa.bbb.ccc --uid 48 --gid 501 /var/www/html/wp-content/uploads3

there is no error in the log:

2016-11-11 06:27:43,839 INFO Version: 2.3.2
2016-11-11 06:27:43,839 INFO s3-retries: '3'
2016-11-11 06:27:43,839 INFO s3-retries-sleep: '1' seconds
2016-11-11 06:27:43,839 INFO S3 bucket: 'aaa.bbb.ccc'
2016-11-11 06:27:43,839 INFO S3 prefix (can be empty): ''
2016-11-11 06:27:43,839 INFO Cache entries: '100000'
2016-11-11 06:27:43,839 INFO Cache memory size (in bytes): '134217728'
2016-11-11 06:27:43,839 INFO Cache disk size (in bytes): '1073741824'
2016-11-11 06:27:43,839 INFO Cache on disk if file size greater than (in bytes): '0'
2016-11-11 06:27:43,839 INFO Cache check interval (in seconds): '5'
2016-11-11 06:27:43,839 INFO Cache ENOENT rechecks S3: False
2016-11-11 06:27:43,839 INFO AWS Managed Encryption enabled: False
2016-11-11 06:27:43,839 INFO AWS Managed Encryption enabled: False
2016-11-11 06:27:43,839 INFO Number of parallel S3 threads (0 to disable writeback): '32'
2016-11-11 06:27:43,839 INFO Number of parallel downloading threads: '4'
2016-11-11 06:27:43,839 INFO Number download retry attempts: '60'
2016-11-11 06:27:43,839 INFO Download retry sleep time seconds: '1'
2016-11-11 06:27:43,839 INFO Number read retry attempts: '10'
2016-11-11 06:27:43,839 INFO Read retry sleep time seconds: '1'
2016-11-11 06:27:43,840 INFO Number of parallel prefetching threads: '2'
2016-11-11 06:27:43,840 INFO Download buffer size (in KB, 0 to disable buffering): '10485760'
2016-11-11 06:27:43,840 INFO Number of buffers to prefetch: '0'
2016-11-11 06:27:43,840 INFO Write metadata (file system attr/xattr) on S3: 'True'
2016-11-11 06:27:43,840 INFO Download prefetch: 'False'
2016-11-11 06:27:43,840 INFO Multipart size: '104857600'
2016-11-11 06:27:43,840 INFO Multipart maximum number of parallel threads: '4'
2016-11-11 06:27:43,840 INFO Multipart maximum number of retries per part: '3'
2016-11-11 06:27:43,840 INFO Default expiration for signed URLs via xattrs: '2592000'
2016-11-11 06:27:43,840 INFO S3 Request Payer: 'False'
2016-11-11 06:27:43,840 INFO Cache path (on disk): '/tmp/yas3fs/aaa.bbb.ccc'
2016-11-11 06:27:43,847 INFO Unique node ID: '5714d075-a53f-4ea2-9b0e-d38e7bb67fab'

however, it is not mounted correctly:

ls: cannot access /var/www/html/wp-content/uploads3: Bad address
total 52
drwxrwsr-x 14 apache   www 4096 11. Nov 06:27 .
d?????????  ? ?        ?      ?             ? uploads3
drwxrwsr-x  2 apache   www 4096  5. Nov 09:10 w3tc-config

I tried a bucket-name without a "." inside and this was working fine. However, I can't avoid the dot as it is needed for the dns-configuration.

Am I missing something?
Thanks
Phil

**Comment by ruffle-b** [comment] 2016-11-19 16:17
Similar issue for me with bucket names with periods.

"yas3fs s3://hello-banana /mnt/hello" works fine.

"yas3fs s3://hello.banana /mnt/hello" doesn't and produces:

> 2016-11-19 16:09:17,010 INFO Default expiration for signed URLs via xattrs: '2592000'
2016-11-19 16:09:17,010 INFO S3 Request Payer: 'False'
2016-11-19 16:09:17,010 INFO Cache path (on disk): '/tmp/yas3fs/hello.banana'
2016-11-19 16:09:17,252 ERROR Uncaught Exception: <class 'ssl.CertificateError'> hostname 'hello.banana.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com' <traceback object at 0x7f748f9ae878>
> None

Yas3fs Version 2.3.2 on ubuntu xenial ec2.

Happy to test/try things but I guess this will be pretty easy to replicate.

Any suggestions on a workaround or fix?

**Comment by dacut** [comment] 2016-11-27 07:32
This is a duplicate of https://github.com/danilop/yas3fs/issues/137 -- see there for the pull request I created for this.

Alternatively, try cloning https://github.com/dacut/yas3fs.git  and run a `sudo python ./setup.py install` to see if that fixes it.

**Comment by dacut** [comment] 2016-11-27 07:56
Related pull request: https://github.com/danilop/yas3fs/pull/139

**Comment by ruffle-b** [comment] 2016-11-28 12:36
Well done.  On an exhaustive test of mounting one bucket containing a period in it's name the above version works :-)

I'll test more over the coming days but it looks good.

Thanks.

**Comment by joshuatalb** [comment] 2017-02-28 01:32
@ruffle-b did you get around to testing it? very interested to know if this works -- thanks!

**Comment by Liath** [comment] 2017-03-10 20:44
Merged, thank you for reporting.

**Closed by Liath** 2017-03-10 20:44 UTC
